# ==========================================
# 1. APACHE ICEBERG CONFIGURATIONS 
# ==========================================
spark.jars.packages                    org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1
spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg_catalog            org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg_catalog.type       hadoop
spark.sql.catalog.iceberg_catalog.warehouse  ./.tmp/local_iceberg_warehouse
spark.sql.defaultCatalog                     iceberg_catalog

# ==========================================
# 2. LOCAL MEMORY & NETWORK SECURITY
# ==========================================
# Give the driver massive headroom for Pandas conversions and caching
spark.driver.memory                    16g
# Prevent crashes when running .collect() on large dataframes
spark.driver.maxResultSize             4g
# M1 Max has 10 cores. Setting partitions to 20 (2x cores) ensures perfect task distribution
spark.sql.shuffle.partitions           20
# Hides Spark from network port scanners to prevent HTTP POST crashes
spark.driver.bindAddress               127.0.0.1
spark.driver.host                      127.0.0.1

# ==========================================
# 3. DEVELOPER EXPERIENCE & STANDARDS
# ==========================================
spark.sql.session.timeZone             UTC
spark.ui.showConsoleProgress           true
spark.sql.repl.eagerEval.enabled       true

# Tells your Jupyter notebook where to WRITE the logs
spark.eventLog.enabled                 true
spark.eventLog.dir                     ./.tmp/spark-events
# Tells the History Server where to READ the logs
spark.history.fs.logDirectory          ./.tmp/spark-events

# SPARK OPTIMIZATIONS
spark.sql.adaptive.enabled             true
